name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Set locale
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US:en
          export LC_ALL=en_US.UTF-8

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: |
          mkdir -p build

          file -i README.md
          head README.md

      - name: Copy images directory (if exists)
        run: | 
          if [[ -d img ]]; then cp -R img build/img; fi

          file -i README.md
          head README.md

      # Add Marp-specific metadata to the Markdown file before translation
      - name: Insert Marp Style Block
        run: |
          file -i README.md
          head README.md

          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8

          file -i README.md
          head README.md

          echo "---" > marp_README.md
          echo "marp: true" >> marp_README.md
          echo "style: |" >> marp_README.md
          echo "  section {" >> marp_README.md
          echo "    background-image: url('./img/DDX_Logo.svg');" >> marp_README.md
          echo "    background-size: 20%;" >> marp_README.md
          echo "    background-repeat: no-repeat;" >> marp_README.md
          echo "    background-position: 95% 30px;" >> marp_README.md
          echo "  }" >> marp_README.md
          echo "---" >> marp_README.md

          cat README.md >> marp_README.md
        shell: bash

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md --allow-local-files -o build/README.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: README.md --allow-local-files -o build/README.pptx
        env:
          MARP_USER: root:root

      - name: Check file encoding and content
        run: |
          file -i README.md
          head README.md

          file -i marp_README.md
          head marp_README.md

      - name: Check if docs folder exists
        id: docs-folder-exists
        run: bash -c "[[ -d docs ]] ; echo \"has_docs=\$?\" >> \"$GITHUB_OUTPUT\""

      - name: Marp Build (docs folder, if exists)
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: -I docs/ -o build/docs/
        env:
          MARP_USER: root:root

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/